---
title: "Assignment 2 question 2"
author: "Lim Zhen Xien"
date: "3 October 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown


#Question2
First we create the decrement table
```{r}
nu_rate = 0.08; u_rate = 0.1
qw = c(0.25, 0.2, 0.175, rep(0.15,6),1)
qx = c(43, 42, 41, 40, 41, 42, 43, 45, 49, 53)/1e5
aqd = qx*(1-0.5*qw); aqw = qw*(1-0.5*qx)
l = numeric(); l[1] = 100000
ald = numeric(); alw = numeric()
```

```{r}
for(i in 1:10){ald[i] = l[i]*aqd[i]; alw[i] = l[i]*aqw[i]; if(i <10){l[i+1] = l[i] - ald[i] - alw[i]}}
```

```{r}
cbind(qx, qw, aqd, aqw,round(cbind(l, ald, alw),0))
```

#unit fund
```{r}
premium_b = rep(5000,10)
asset_fee = 0.003
bs = 0.005
p_fee_b = c(0.45, rep(0.01, 9))
```

```{r}
invest_premium_b = premium_b*(1-p_fee_b)*(1-bs)
unit_fund_value_e = numeric()
unit_fund_value_e[1] = invest_premium_b[1]*(1+u_rate)*(1-asset_fee)
```

```{r}
for(i in 2:10){unit_fund_value_e[i] = (unit_fund_value_e[i-1] + invest_premium_b[i])*(1+u_rate)*(1-asset_fee)}
invest_premium = invest_premium_b * l[1:10]/l[1]
```

```{r}
unit_fund_value = unit_fund_value_e * c(l[2:10],0)/l[1]
int_unit = (invest_premium+c(0, unit_fund_value[1:9]))*u_rate
```

```{r}
transfer_to_nunit = (invest_premium + int_unit - unit_fund_value)[1]
for(i in 2:10){transfer_to_nunit[i] = (invest_premium + int_unit - diff(c(0, unit_fund_value)))[i]}
unit = cbind(invest_premium, int_unit, unit_fund_value, transfer_to_nunit)
unit
```

#non-unit fund
```{r}
acq_fee = c(0.45, rep(0,9))*premium_b
p_related_fee_b = premium_b * p_fee_b
bs_margin_b = premium_b*(1-p_fee_b)*bs
exp_b = 58*(1+0.2)^(0:9); exp_b[1] = exp_b[1] + 0.45*premium_b[1]
benefit_e = unit_fund_value_e
```

```{r}
p_related_fee = p_related_fee_b * l/l[1]
exp = exp_b * l/l[1]
bs_margin = bs_margin_b * l/l[1]
nu_int = (p_related_fee + bs_margin - exp)*nu_rate
dreathben = benefit_e * ald/l[1]
withdrawben = benefit_e * alw/l[1]
```

```{r}
transfer = p_related_fee + bs_margin + nu_int - exp - dreathben - withdrawben + transfer_to_nunit
cbind(p_related_fee, bs_margin, exp, nu_int, dreathben, withdrawben, transfer_to_nunit, transfer)
```

```{r}
increase = function(amount){
  nu_rate = 0.08; u_rate = 0.1
  qw = c(0.25, 0.2, 0.175, rep(0.15,6),1)
  qx = c(43, 42, 41, 40, 41, 42, 43, 45, 49, 53)/1e5
  aqd = qx*(1-0.5*qw); aqw = qw*(1-0.5*qx)
  l = numeric(); l[1] = 100000
  ald = numeric(); alw = numeric()
  for(i in 1:10){ald[i] = l[i]*aqd[i]; alw[i] = l[i]*aqw[i]; if(i <10){l[i+1] = l[i] - ald[i] - alw[i]}}
```

#unit fund
```{r}
premium_b = rep(5000,10)
asset_fee = 0.003
bs = 0.005
p_fee_b = c(0.45, rep(0.01, 9))
```

```{r}
invest_premium_b = premium_b*(1-p_fee_b)*(1-bs)
```

```{r}
unit_fund_value_e = numeric()
unit_fund_value_e[1] = invest_premium_b[1]*(1+u_rate)*(1-asset_fee)
for(i in 2:10){unit_fund_value_e[i] = (unit_fund_value_e[i-1] +  invest_premium_b[i])*(1+u_rate)*(1-asset_fee)}
```

```{r}
policy_value_e = unit_fund_value_e
policy_value_e[9] = policy_value_e[9] + amount
```

```{r}
invest_premium = invest_premium_b * l[1:10]/l[1]
unit_fund_value = unit_fund_value_e * c(l[2:10],0)/l[1]
```

```{r}
policy_value = policy_value_e * c(l[2:10],0)/l[1]
int_unit = (invest_premium+c(0, policy_value[1:9]))*u_rate
transfer_to_nunit = (invest_premium + int_unit - unit_fund_value)[1]
```

```{r}
for(i in 2:10){transfer_to_nunit[i] = (invest_premium + int_unit - diff(c(0, policy_value)))[i]}
```  
  
#non-unit fund
```{r}
acq_fee = c(0.45, rep(0,9))*premium_b
p_related_fee_b = premium_b * p_fee_b
bs_margin_b = premium_b*(1-p_fee_b)*bs
```

```{r}
exp_b = 58*(1+0.2)^(0:9); exp_b[1] = exp_b[1] + 0.45*premium_b[1]
benefit_e = unit_fund_value_e
```  
```{r}
p_related_fee = p_related_fee_b * l/l[1]
exp = exp_b * l/l[1]
bs_margin = bs_margin_b * l/l[1]
nu_int = (p_related_fee + bs_margin - exp)*nu_rate
dreathben = benefit_e * ald/l[1]
withdrawben = benefit_e * alw/l[1]
```

```{r}
transfer = p_related_fee + bs_margin + nu_int - exp - dreathben - withdrawben + transfer_to_nunit
  return(transfer[10])
}
```

```{r}
npv_new = function(amount){
  nu_rate = 0.08; u_rate = 0.1
  qw = c(0.25, 0.2, 0.175, rep(0.15,6),1)
  qx = c(43, 42, 41, 40, 41, 42, 43, 45, 49, 53)/1e5
  aqd = qx*(1-0.5*qw); aqw = qw*(1-0.5*qx)
  l = numeric(); l[1] = 100000
  ald = numeric(); alw = numeric()
  for(i in 1:10){ald[i] = l[i]*aqd[i]; alw[i] = l[i]*aqw[i]; if(i <10){l[i+1] = l[i] - ald[i] - alw[i]}}
```

#unit fund
```{r}
premium_b = rep(5000,10)
asset_fee = 0.003
bs = 0.005
p_fee_b = c(0.45, rep(0.01, 9))
```

```{r}
invest_premium_b = premium_b*(1-p_fee_b)*(1-bs)
unit_fund_value_e = numeric()
unit_fund_value_e[1] = invest_premium_b[1]*(1+u_rate)*(1-asset_fee)
```

```{r}
for(i in 2:10){unit_fund_value_e[i] = (unit_fund_value_e[i-1] +  invest_premium_b[i])*(1+u_rate)*(1-asset_fee)}
policy_value_e = unit_fund_value_e
policy_value_e[9] = policy_value_e[9] + amount
invest_premium = invest_premium_b * l[1:10]/l[1]
```

```{r}
unit_fund_value = unit_fund_value_e * c(l[2:10],0)/l[1]
policy_value = policy_value_e * c(l[2:10],0)/l[1]
int_unit = (invest_premium+c(0, policy_value[1:9]))*u_rate
```

```{r}
transfer_to_nunit = (invest_premium + int_unit - unit_fund_value)[1]
for(i in 2:10){transfer_to_nunit[i] = (invest_premium + int_unit - diff(c(0, policy_value)))[i]}
```

  
#non-unit fund
```{r}
acq_fee = c(0.45, rep(0,9))*premium_b
p_related_fee_b = premium_b * p_fee_b
bs_margin_b = premium_b*(1-p_fee_b)*bs
exp_b = 58*(1+0.2)^(0:9); exp_b[1] = exp_b[1] + 0.45*premium_b[1]
benefit_e = unit_fund_value_e
```

```{r}
p_related_fee = p_related_fee_b * l/l[1]
exp = exp_b * l/l[1]
bs_margin = bs_margin_b * l/l[1]
nu_int = (p_related_fee + bs_margin - exp)*nu_rate
dreathben = benefit_e * ald/l[1]
withdrawben = benefit_e * alw/l[1]
```

```{r}  
transfer = p_related_fee + bs_margin + nu_int - exp - dreathben - withdrawben + transfer_to_nunit
  return(sum(transfer/(1.125)^(1:10)))
}
```

#(a)transfer
```{r}
sum(transfer/(1.125)^(1:10))
```

#(b)
```{r}
uniroot(increase, c(3,4))[1]
```

#(c)
```{r}
npv_new(3.713458)
```
